# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-04 22:12:52
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
def #  NOT  IMPLEMENTED# Function Body not implemented

def Rescale():  # Rescale

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\GAMLab\\DenverUrbanHeat\\Veg\\pt2\\MyProject\\MyProject.gdb", workspace="D:\\GAMLab\\DenverUrbanHeat\\Veg\\pt2\\MyProject\\MyProject.gdb"):
        ev23_gdb = "D:\\GAMLab\\DenverUrbanHeat\\Veg\\pt2\\MyProject\\ev23.gdb"

        for Raster, Name in #  NOT  IMPLEMENTED(ev23_gdb, "", "", "NOT_RECURSIVE"):

            # Process: Raster Calculator (Raster Calculator) (sa)
            Name = "US_eVSH_NDVI_2023_318_324_3KM_VI_NDVI_001_2023327181441"
            _Name_rs = fr"D:\GAMLab\DenverUrbanHeat\Veg\pt2\MyProject\Rescale.gdb\{Name}_rs"
            Raster_Calculator = _Name_rs
            _Name_rs =  Raster * 0.0001
            _Name_rs.save(Raster_Calculator)


            # Process: Extract by Mask (Extract by Mask) (sa)
            Output_raster = "D:\\GAMLab\\DenverUrbanHeat\\Veg\\pt2\\MyProject\\MyProject.gdb\\Extract_Nam1"
            Extract_by_Mask = Output_raster
            Output_raster = arcpy.sa.ExtractByMask(_Name_rs, "", "INSIDE", "-2050500 -2136500 2536125 752500 PROJCS[\"LAEA_Sphere_19\",GEOGCS[\"\",DATUM[\"D_unknown\",SPHEROID[\"Sphere\",6370997.0,0.0]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-100.0],PARAMETER[\"latitude_of_origin\",45.0],UNIT[\"Meter\",1.0]]")
            Output_raster.save(Extract_by_Mask)


if __name__ == '__main__':
    Rescale()
